name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.8
        
      
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        #run: bandit -r .
        #run: bandit -ll -ii -r .
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json
    
  image_scan:
    name: Buikd Image and Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.9.3
      
      
        
      

      

      
