name: Dependency Check

on: 
  workflow_dispatch:
  
jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip
        unzip dependency-check-8.2.1-release.zip -d dependency-check
        ls -R dependency-check  # List files for diagnosis

    - name: Run OWASP Dependency-Check
      run: |
        ls -R dependency-check  # List files for diagnosis
        ./dependency-check/bin/dependency-check.sh --project "PyGoat" --scan ${{ github.workspace }} --format JSON --out ${{ github.workspace }}/odc-reports

    - name: Upload dependency check report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: odc-reports/dependency-check-report.json
