name: Dependency Check

on:
 workflow_dispatch:
 
jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create report directory
      run: mkdir -p odc-reports

    - name: Run OWASP Dependency-Check
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: |
        docker run --rm \
          --volume $(pwd):/src \
          --volume $(pwd)/odc-reports:/report \
          owasp/dependency-check \
          --project "PyGoat" \
          --scan /src \
          --format JSON \
          --out /report

    - name: Upload dependency check report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: odc-reports/dependency-check-report.json
