name: OWASP Dependency-Check

on:
 workflow_dispatch:
 
jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run OWASP Dependency-Check
        run: |
          docker pull owasp/dependency-check
          docker run --rm \
            -v $(pwd)/odc-reports:/report \
            -v $(pwd):/src \
            owasp/dependency-check \
            --format "ALL" \
            --project "My Project" \
            --scan /src
          
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: odc-reports
